### ISSUE TITLE
可以支持微信小程序吗？

### ISSUE THREAD

**Issue by ado5** [karasjs/karas#138]
可以支持微信小程序吗？如果可以支持小程序的canvas那真的是太好了~

**Comment by army8735** [comment]
好，估计和my-karas小程序差不多

**Comment by army8735** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/canvas/Canvas.createImage.html

https://developers.weixin.qq.com/miniprogram/dev/api/canvas/Image.html

image比较特殊，需改造

**Comment by army8735** [comment]
demo良好运行
![image](https://user-images.githubusercontent.com/174904/107903401-1c886880-6f84-11eb-85c0-eae3e9cb42a0.png)
